version: '3.4'

services:
  productapi:
    image: productapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo/mirrAR
    ports:
      - 8080:8080
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
